/**
 * Habbit Türkçe Arayüz ve Metin Sabitleri
 * Tüm kullanıcı arayüzü istisnasız Türkçedir.
 */

export const STRINGS = {
  app: {
    name: 'Ritim',
    tagline: 'Sakin, odaklı ve bilinçli alışkanlıklar',
  },
  tabs: {
    today: 'Bugün',
    calendar: 'Takvim',
    statistics: 'İstatistikler',
    areas: 'Alanlar',
  },
  today: {
    title: 'Bugün',
    dailyProgress: 'Günlük İlerleme',
    allHabitsCompleted: 'Tebrikler! Bugünün tüm alışkanlıklarını tamamladın.',
    noHabitsToday: 'Bugün için planlanmış bir alışkanlık yok.',
    createFirstHabit: 'İlk alışkanlığını oluşturarak güne başla.',
    filterAll: 'Tümü',
    filterBuild: 'Kazanılanlar',
    filterQuit: 'Bırakılanlar',
    streakStatus: 'Mevcut Seri',
    longestStreak: 'En Uzun',
    quickComplete: 'Tamamla',
    quickRelapse: 'Nüksetti',
    cleanDayActive: 'Temiz Gün Devam Ediyor',
  },
  calendar: {
    title: 'Takvim',
    goToToday: 'Bugüne Git',
    monthCompletionRate: 'Aylık Başarı Oranı',
    dayDetails: 'Günün Detayları',
    noHabitsForDay: 'Bu tarihte planlanmış bir alışkanlık bulunmuyor.',
    editLog: 'Kaydı Düzenle',
    saveNote: 'Not Kaydet',
    notePlaceholder: 'Bu gün hakkında bir not ekle...',
  },
  statistics: {
    title: 'İstatistikler',
    period7Days: 'Son 7 Gün',
    period30Days: 'Son 30 Gün',
    periodMonth: 'Bu Ay',
    periodYear: 'Bu Yıl',
    periodAll: 'Tüm Zamanlar',
    completionRate: 'Başarı Oranı',
    currentStreak: 'Mevcut Seri',
    longestStreak: 'En Uzun Seri',
    totalCompletions: 'Toplam Tamamlama',
    bestDay: 'En Başarılı Gün',
    weeklyConsistency: 'Haftalık Tutarlılık',
    habitsOverview: 'Alışkanlık Başarı Dağılımı',
    noDataForPeriod: 'Bu dönem için henüz yeterli veri bulunmuyor.',
  },
  areas: {
    title: 'Yaşam Alanları',
    subtitle: 'Hayatının farklı boyutlarındaki gelişim dengesi',
    newArea: 'Yeni Alan Ekle',
    editArea: 'Alanı Düzenle',
    areaName: 'Alan Adı',
    areaColor: 'Renk',
    areaIcon: 'İkon',
    activeHabitsCount: (count: number) => `${count} Alışkanlık`,
    weeklyRate: 'Haftalık Başarı',
    deleteAreaConfirm: 'Bu alanı silmek istediğinize emin misiniz? Alana ait alışkanlıklar silinmez, bağımsız hale gelir.',
    noAreasYet: 'Henüz bir yaşam alanı eklemediniz.',
  },
  habitForm: {
    createTitle: 'Yeni Alışkanlık',
    editTitle: 'Alışkanlığı Düzenle',
    typeBuild: 'Alışkanlık Kazan',
    typeBuildDesc: 'Hayatına katmak istediğin olumlu eylemler',
    typeQuit: 'Alışkanlığı Bırak',
    typeQuitDesc: 'Terk etmek veya azaltmak istediğin davranışlar',
    nameLabel: 'Alışkanlık Adı',
    namePlaceholder: 'Örn: Kitap Oku, Günde 2L Su',
    descLabel: 'Açıklama veya Neden (Opsiyonel)',
    descPlaceholder: 'Bunu neden yapıyorsun? Seni ne motive ediyor?',
    areaLabel: 'Yaşam Alanı',
    noAreaOption: 'Alan Seçilmedi',
    iconAndColorLabel: 'İkon ve Renk',
    trackingModeLabel: 'Takip Modu',
    modeBoolean: 'Evet / Hayır',
    modeBooleanDesc: 'Günde bir kez yapıldı olarak işaretlenir',
    modeNumeric: 'Sayısal Hedef',
    modeNumericDesc: 'Örn: 20 sayfa, 8 bardak, 5 kilometre',
    modeDuration: 'Süre Hedefi',
    modeDurationDesc: 'Örn: 45 dakika çalışma veya meditasyon',
    targetValueLabel: 'Günlük Hedef',
    unitLabel: 'Birim (Sayfa, Bardak, km vb.)',
    durationMinutesLabel: 'Hedef Süre (Dakika)',
    frequencyLabel: 'Tekrar Planı',
    freqDaily: 'Her Gün',
    freqWeekdays: 'Yalnızca Hafta İçi',
    freqWeekends: 'Yalnızca Hafta Sonu',
    freqSpecificDays: 'Seçili Günler',
    freqInterval: 'Aralıklı (N Günde Bir)',
    intervalDaysLabel: 'Kaç günde bir tekrarlansın?',
    streakGoalLabel: 'Seri Hedefi (Gün)',
    remindersLabel: 'Hatırlatıcılar',
    addReminder: '+ Hatırlatıcı Ekle',
    saveHabit: 'Alışkanlığı Kaydet',
    updateHabit: 'Değişiklikleri Kaydet',
    validationNameRequired: 'Lütfen alışkanlık adını giriniz.',
    validationTargetPositive: 'Hedef değer 0\'dan büyük olmalıdır.',
  },
  habitDetail: {
    currentStreak: 'Mevcut Seri',
    longestStreak: 'Rekor Seri',
    streakGoal: 'Seri Hedefi',
    completionHistory: 'Tamamlama Geçmişi',
    historyHeatmap: 'Aktivite Isı Haritası',
    recentLogs: 'Son Kayıtlar',
    actions: 'İşlemler',
    edit: 'Alışkanlığı Düzenle',
    archive: 'Alışkanlığı Arşivle',
    unarchive: 'Arşivden Çıkar',
    delete: 'Kalıcı Olarak Sil',
    archiveConfirm: 'Bu alışkanlığı arşivlemek istediğinize emin misiniz? Pano ve takvimden kaldırılacak, ancak geçmiş verileriniz korunacaktır.',
    deleteConfirm: 'Bu alışkanlığı ve TÜM geçmiş kayıtlarını kalıcı olarak silmek istediğinize emin misiniz? Bu işlem geri alınamaz.',
    relapseLogged: 'Nüksetme kaydedildi. Unutma, her düşüş yeni bir başlangıç fırsatıdır.',
  },
  settings: {
    title: 'Ayarlar',
    notificationsSection: 'Bildirimler',
    dailyReview: 'Günlük Değerlendirme',
    dailyReviewDesc: 'Her akşam alışkanlıklarını gözden geçirmen için sakin bir hatırlatma.',
    dailyReviewTime: 'Değerlendirme Saati',
    dashboardSection: 'Pano Özelleştirme',
    compactMode: 'Kompakt Kart Görünümü',
    compactModeDesc: 'Kartları daha az boşlukla ve küçük boyutta gösterir.',
    dataSection: 'Veri ve Yedekleme',
    exportJson: 'Tüm Verileri Dışa Aktar (JSON)',
    exportJsonDesc: 'Veritabanının tam yedeğini oluşturur.',
    exportCsv: 'Aktivite Dökümü İndir (CSV)',
    exportCsvDesc: 'Tablo programlarında incelemek için ideal döküm.',
    importJson: 'Yedekten Geri Yükle',
    importJsonDesc: 'Daha önce aldığınız JSON yedeğinden verileri geri yükler.',
    archiveSection: 'Arşiv',
    archivedHabits: 'Arşivlenen Alışkanlıklar',
    aboutSection: 'Hakkında',
    version: 'Sürüm',
    offlineNotice: 'Ritim tamamen çevrimdışı çalışır. Tüm verileriniz cihazınızda güvenle saklanır.',
    exportSuccess: 'Veriler başarıyla dışa aktarıldı.',
    importSuccess: 'Yedek başarıyla geri yüklendi.',
    importConfirm: 'Mevcut veritabanınız yedek dosyasındaki verilerle değiştirilecek. Devam etmek istiyor musunuz?',
  },
  archive: {
    title: 'Arşivlenen Alışkanlıklar',
    emptyMessage: 'Arşivde hiç alışkanlık bulunmuyor.',
    restore: 'Geri Yükle',
    deletePermanent: 'Kalıcı Sil',
    restoredToast: 'Alışkanlık aktif listeye geri yüklendi.',
  },
  common: {
    save: 'Kaydet',
    cancel: 'Vazgeç',
    delete: 'Sil',
    edit: 'Düzenle',
    close: 'Kapat',
    back: 'Geri',
    confirm: 'Onayla',
    yes: 'Evet',
    no: 'Hayır',
    daysShort: ['Pzt', 'Sal', 'Çar', 'Per', 'Cum', 'Cmt', 'Paz'],
    daysFull: ['Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi', 'Pazar'],
    monthsShort: ['Oca', 'Şub', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağu', 'Eyl', 'Eki', 'Kas', 'Ara'],
    monthsFull: [
      'Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran',
      'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'
    ],
    minute: 'dk',
    unitPage: 'sayfa',
    unitGlass: 'bardak',
    unitKm: 'km',
    dayCount: (n: number) => `${n} gün`,
    percent: (n: number) => `%${Math.round(n)}`,
  },
};
